source "https://rubygems.org"

ruby '~> 2.7.0'

gem 'aws-sdk-ssm', '~> 1.55'
gem 'faraday'
gem 'proofer', github: '18F/identity-doc-auth', tag: 'v0.2.0'
gem 'identity-hostdata', github: '18F/identity-hostdata', tag: 'v0.4.1'
gem 'retries'
gem 'openssl'
