source 'https://rubygems.org'

ruby '~> 2.7.0'

gem 'aws-sdk-ssm', '~> 1.55'
gem 'faraday'
gem 'identity-doc-auth', github: '18F/identity-doc-auth', tag: 'v0.3.0'
gem 'openssl'
gem 'proofer', github: '18F/identity-proofer-gem', tag: 'v2.7.0'
gem 'retries'
