source 'https://rubygems.org'

ruby '~> 2.7.0'

gem 'aws-sdk-s3'
gem 'aws-sdk-ssm', '~> 1.55'
gem 'faraday'
gem 'identity-doc-auth', github: '18F/identity-doc-auth', tag: 'v0.3.1'
gem 'openssl'
gem 'retries'
