version: 2.1

executors:
  ubuntu-2004:
    machine:
      image: ubuntu-2004:202008-01

workflows:
  lambda-functions:
    jobs:
      - lints
      - build-specs
      - build-package:
          filters:
            branches:
              ignore:
                - master
          requires:
            - build-specs
          context:
            - login-sandbox
            - login-prod
      - build-package-copy:
          filters:
            branches:
              only:
                - master
          requires:
            - build-specs
          context:
            - login-sandbox
            - login-prod

jobs:
  build-specs:
    executor: ubuntu-2004
    steps:
      - checkout
      - run-specs

  lints:
    executor: ubuntu-2004
    steps:
      - checkout
      - run-lints

  build-package:
    executor: ubuntu-2004
    steps:
      - brew-install
      - aws-cli-configure
      - sam-cli-install
      - checkout
      - build-repo

  build-package-copy:
    executor: ubuntu-2004
    steps:
      - brew-install
      - aws-cli-configure
      - aws-cli-configure-prod
      - sam-cli-install
      - checkout
      - build-repo
      - copy-to-s3
      - copy-to-s3-prod

commands:
  sam-cli-install:
    steps:
      - run:
          name: "Install SAM CLI"
          command: |
            PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
            brew tap aws/tap
            # brew install aws-sam-cli
            # hack to fix broken brew install of aws-sam-cli
            brew reinstall python@3.7
            pip3 install aws-sam-cli
            sam --version

  brew-install:
    steps:
      - run:
          name: "Install Brew"
          command: |
            sudo apt-get install build-essential
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
            echo 'export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH' >> /home/circleci/.bash_profile
            eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            brew --version

  bundle-install:
    steps:
      - run: gem update --system
      - run: gem install bundler
      - restore_cache:
          keys:
            - v2-identity-idp-functions-bundle-{{ checksum "Gemfile" }}
      - run: bundle config set path vendor/bundle
      - run: bundle check || bundle install
      - save_cache:
          key: v2-identity-idp-functions-bundle-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle

  aws-cli-install:
    steps:
      - run:
          name: "Install AWS CLI"
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

  aws-cli-configure:
    steps:
      - run:
          name: "Configure AWS CLI"
          command: |
            aws configure set default.aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set default.aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION

  aws-cli-configure-prod:
    steps:
      - run:
          name: "Configure AWS CLI Prod"
          command: |
            aws configure set profile.prod.aws_access_key_id $prod_AWS_ACCESS_KEY_ID
            aws configure set profile.prod.aws_secret_access_key $prod_AWS_SECRET_ACCESS_KEY
            aws configure set profile.prod.region $AWS_DEFAULT_REGION

  generate-template-yaml:
    steps:
      - bundle-install
      - run:
          name: "Generate source/template.yaml"
          command: |
            ./bin/generate-template > source/template.yaml

  build-repo:
    steps:
      - generate-template-yaml
      - run:
          name: "Validate SAM template"
          command: |
            PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
            cd source
            sam validate -t template.yaml --profile default --debug
      - run:
          name: "Build Functions"
          command: |
            PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
            cd source
            sam build \
              --template template.yaml \
              --use-container
      - run:
          name: "Test Functions"
          command: |
            cd source
      - run:
          name: "Package Functions"
          command: |
            PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
            cd source
            sam package \
              --profile default \
              --debug \
              --s3-bucket $DEPLOY_S3_BUCKET \
              --s3-prefix circleci/identity-idp-functions/$CIRCLE_BRANCH/packages \
              --output-template-file identity-idp-functions.template.yaml
            echo $CIRCLE_SHA1 > gitsha.txt
            zip identity-idp-functions.zip identity-idp-functions.template.yaml
            zip identity-idp-functions.zip buildspec.yml
            zip identity-idp-functions.zip gitsha.txt

  copy-to-s3:
    steps:
      - run:
          name: "Copy packages to S3"
          command: |
            cd source
            aws s3 cp identity-idp-functions.template.yaml s3://$DEPLOY_S3_BUCKET/circleci/identity-idp-functions/$CIRCLE_BRANCH/
            aws s3 cp identity-idp-functions.zip s3://$DEPLOY_S3_BUCKET/circleci/identity-idp-functions/$CIRCLE_BRANCH/

  copy-to-s3-prod:
    steps:
      - run:
          name: "Copy packages to S3 prod"
          command: |
            cd source
            aws s3 cp identity-idp-functions.template.yaml s3://$prod_DEPLOY_S3_BUCKET/circleci/identity-idp-functions/$CIRCLE_BRANCH/ --profile prod
            aws s3 cp identity-idp-functions.zip s3://$prod_DEPLOY_S3_BUCKET/circleci/identity-idp-functions/$CIRCLE_BRANCH/ --profile prod

  run-specs:
    steps:
      - bundle-install
      - run:
          name: Run rspec
          command: bundle exec rake spec

  run-lints:
    steps:
      - bundle-install
      - run:
          name: Run rubocop
          command: bundle exec rubocop
