version: 2.1

executors:
  aws:
    docker:
      - image: amazon/aws-sam-cli-build-image-ruby2.7

workflows:
  lambda-functions:
    jobs:
      - lints
      - build-specs
      - build-package:
          filters:
            branches:
              ignore:
                - main
          requires:
            - build-specs
          context:
            - login-sandbox
            - login-prod
      - build-package-copy:
          filters:
            branches:
              only:
                - main
          requires:
            - build-specs
          context:
            - login-sandbox
            - login-prod

jobs:
  build-specs:
    executor: aws
    steps:
      - checkout
      - run-specs

  lints:
    executor: aws
    steps:
      - checkout
      - run-lints

  build-package:
    executor: aws
    steps:
      - aws-cli-configure
      - checkout
      - build-repo
      - copy-to-s3

  build-package-copy:
    executor: aws
    steps:
      - aws-cli-configure
      - aws-cli-configure-prod
      - checkout
      - build-repo
      - copy-to-s3
      - copy-to-s3-prod

commands:
  bundle-install:
    steps:
      - run: gem update --system --no-document
      - run: gem install bundler
      - run: bundle install --path vendor/bundle

  aws-cli-configure:
    steps:
      - run:
          name: "Configure AWS CLI"
          command: |
            yum install openssl-devel -y
            aws configure set default.aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set default.aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION

  aws-cli-configure-prod:
    steps:
      - run:
          name: "Configure AWS CLI Prod"
          command: |
            aws configure set profile.prod.aws_access_key_id $prod_AWS_ACCESS_KEY_ID
            aws configure set profile.prod.aws_secret_access_key $prod_AWS_SECRET_ACCESS_KEY
            aws configure set profile.prod.region $AWS_DEFAULT_REGION

  generate-template-yaml:
    steps:
      - bundle-install
      - run:
          name: "Generate source/template.yaml"
          command: |
            ./bin/generate-template > source/template.yaml

  build-repo:
    steps:
      - generate-template-yaml
      - run:
          name: "Validate SAM template"
          command: |
            cd source
            sam validate -t template.yaml --profile default --debug
      - run:
          name: "Build Functions"
          command: |
            cd source
            sam build \
              --template template.yaml
      - run:
          name: "Test Functions"
          command: |
            cd source
      - run:
          name: "Package Functions"
          command: |
            cd source
            sam package \
              --profile default \
              --debug \
              --s3-bucket $DEPLOY_S3_BUCKET \
              --s3-prefix circleci/identity-idp-functions/$CIRCLE_BRANCH/packages \
              --output-template-file identity-idp-functions.template.yaml
            echo $CIRCLE_SHA1 > gitsha.txt
            zip identity-idp-functions.zip identity-idp-functions.template.yaml
            zip identity-idp-functions.zip buildspec.yml
            zip identity-idp-functions.zip gitsha.txt

  copy-to-s3:
    steps:
      - run:
          name: "Copy packages to S3"
          command: |
            cd source
            aws s3 cp identity-idp-functions.template.yaml s3://$DEPLOY_S3_BUCKET/circleci/identity-idp-functions/$CIRCLE_BRANCH/
            aws s3 cp identity-idp-functions.zip s3://$DEPLOY_S3_BUCKET/circleci/identity-idp-functions/$CIRCLE_BRANCH/

  copy-to-s3-prod:
    steps:
      - run:
          name: "Copy packages to S3 prod"
          command: |
            cd source
            aws s3 cp identity-idp-functions.template.yaml s3://$prod_DEPLOY_S3_BUCKET/circleci/identity-idp-functions/$CIRCLE_BRANCH/ --profile prod
            aws s3 cp identity-idp-functions.zip s3://$prod_DEPLOY_S3_BUCKET/circleci/identity-idp-functions/$CIRCLE_BRANCH/ --profile prod

  run-specs:
    steps:
      - bundle-install
      - run:
          name: Run rspec
          command: bundle exec rake spec

  run-lints:
    steps:
      - bundle-install
      - run:
          name: Run rubocop
          command: bundle exec rubocop
