source 'https://rubygems.org'

ruby '~> 2.7.0'

gem 'aws-sdk-ssm', '~> 1.55'
gem 'faraday'
gem 'lexisnexis', github: '18F/identity-lexisnexis-api-client-gem', tag: 'v2.4.1'
gem 'proofer', git: 'https://github.com/18F/identity-proofer-gem.git', ref: 'd64adb3'
gem 'retries'
