AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  gitsha:
    Type: String
    Description: Git sha
  environment:
    Type: String
    Description: Deployment environment
    Default: "dev"

Metadata:
  AWS::ServerlessRepo::Application:
    Name: login-idp-functions
    Description: login.gov idp functions
    Author: logindotgov
    SpdxLicenseId: CC0-1.0
    HomePageUrl: https://github.com/18f/identity-idp-functions
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/18f/identity-idp-functions
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Application Settings
        Parameters:
          - gitsha
          - environment

Description: >
  identity-idp-functions

  IDP functions for login.gov

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Runtime: ruby2.7

Resources:
  DemoFunctionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: demo_function/src/
      Handler: handler.Identity::Idp::Functions::DemoFunction.handle
      MemorySize: 128
      AutoPublishAlias: !Ref environment
      DeploymentPreference:
        Type: AllAtOnce
      VersionDescription: !Ref gitsha
      Layers:
        - !Ref AWSRubySDKLayer
      Environment:
        Variables:
          S3_BUCKET_NAME: !Sub
            - login-gov-idp-doc-capture-${Environment}.${AccountId}-${Region}
            - Environment: !Ref environment
              AccountId: !Ref AWS::AccountId
              Region: !Ref AWS::Region
          KMS_KEY_ALIAS: !Sub
            - ${Environment}-idp-doc-capture
            - Environment: !Ref environment
          ENVIRONMENT_NAME: !Ref environment
      Policies:
        - Statement:
          - Sid: S3ObjectAccess
            Effect: Allow
            Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            Resource: !Sub
              - arn:aws:s3:::login-gov-idp-doc-capture-${Environment}.${AccountId}-${Region}/*
              - Environment: !Ref environment
                AccountId: !Ref AWS::AccountId
                Region: !Ref AWS::Region
        - Statement:
          - Sid: S3BucketAccess
            Effect: Allow
            Action:
            - s3:ListBucket
            Resource: !Sub
              - arn:aws:s3:::login-gov-idp-doc-capture-${Environment}.${AccountId}-${Region}
              - Environment: !Ref environment
                AccountId: !Ref AWS::AccountId
                Region: !Ref AWS::Region
        - Statement:
          - Sid: KMS
            Effect: Allow
            Action:
              - kms:GenerateDataKey
              - kms:Encrypt
              - kms:DescribeKey
              - kms:Decrypt
            Resource: !Sub
              - '{{resolve:ssm:/${Environment}/idp/lambda/upload/kms/arn:1}}'
              - Environment: !Ref environment
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt DemoFunctionSecurityGroup.GroupId
        SubnetIds:
          - !Sub
              - '{{resolve:ssm:/${Environment}/network/subnet/private1/id:1}}'
              - Environment: !Ref environment
          -  !Sub
              - '{{resolve:ssm:/${Environment}/network/subnet/private2/id:1}}'
              - Environment: !Ref environment
          - !Sub
              - '{{resolve:ssm:/${Environment}/network/subnet/private3/id:1}}'
              - Environment: !Ref environment
      Tags:
        environment: !Ref environment

  DemoFunctionFunctionArn:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub
        - /${Environment}/idp/lambda/DemoFunction/arn
        - Environment: !Ref environment
      Value: !GetAtt DemoFunctionFunction.Arn

  DemoFunctionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Sub
        - '{{resolve:ssm:/${Environment}/network/vpc/id:1}}'
        - Environment: !Ref environment
      GroupDescription: Hello World Lambda Function
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          # Should be another security group or VPC CIDR block
          CidrIp: 0.0.0.0/0

  AWSRubySDKLayer:
    Type: "AWS::Serverless::LayerVersion"
    Properties:
      Description: AWS Ruby SDK
      ContentUri: aws-ruby-sdk
      CompatibleRuntimes:
        - ruby2.7
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: ruby2.7

Outputs:
  DemoFunctionFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt DemoFunctionFunction.Arn
  DemoFunctionFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt DemoFunctionFunctionRole.Arn
